language: objective-c  #1
osx_image: xcode6.4 #2
#xcode_project: HelloWorld.xcodeproj #3
#xcode_scheme: HelloWorld #4
#xcode_sdk: iphonesimulator8.4
script:
  xctool
  -project HelloWorld.xcodeproj
  -scheme HelloWorld
  -sdk iphonesimulator
  build 
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

#destination 'platform=iOS Simulator,name=iPhone 6 Plus
#before_install:
#  - brew update
#  - brew uninstall xctool && brew install --HEAD xctool
