language: objective-c
osx_image: xcode9
script:
  - xctool -project HelloWorld.xcodeproj -scheme HelloWorld -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project HelloWorld.xcodeproj -scheme HelloWorldTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
