language: objective-c
osx_image: xcode9.1
before_install:
  - brew update
  - brew upgrade xctool
script:
  - xctool -project HelloWorld.xcodeproj -scheme HelloWorld -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
